### ISSUE TITLE
Deploy the system onto a platform of your choice

### ISSUE THREAD

**Issue by hainguyenbizzi** [15110139/blog-project#1]
Hi Tien,

Thanks for your time doing the assignment.
After carefully reviewing your assignment, that's very good so far. However, there is also a required step in the submission part that you should complete:
- Deploy the system onto a platform of your choice

To be clear, you don't have to update the unit test or add CI/CD script.
You just need to deploy your project onto a platform that we can make a test tour on your system.

**Comment by 15110139** [comment]
Sorry for my mistake. I just deploy my application on Azure
